### ISSUE TITLE
Push newest podfile out.

### ISSUE THREAD

**Issue by electic** [Armanoide/VisualHumainNumber#2]

**Comment by Armanoide** [comment]
"Push newest podfile out" yes, but what for ? 
Do you need some special change ?

**Comment by electic** [comment]
When you do pod install, it says it can't find 1.0.7. Where as 1.0.7 in the git repo. I just figured it was not pushed out.

**Comment by Armanoide** [comment]
i fix the issue with **1.0.8**. Don't forget by the way to do `pod install --repo-update`

**Comment by electic** [comment]
Thank you. Great pod btw!
