### ISSUE TITLE
Negative numbers are not supported

### ISSUE THREAD

**Issue by hey-amo** [Armanoide/VisualHumainNumber#3]
Just tried a few numbers in Swift playgrounds, but negative numbers do not seem supported.

let vhn: VisualHumainNumber = VisualHumainNumber(string: "-53430345.83", separator: ",");
print (vhn.getVisualHumainNumbers(notation: .simpleHumain))

// output is 53.4M
// expected is -53.4M

let text = VisualHumainNumber(long: -101800, separator: "," ).getVisualHumainNumbers(notation: VisualHumainNumberNotation.simpleHumain)
print (text)

// output is 101,800
// expected: -101k

**Comment by Armanoide** [comment]
it was suppose to use with positive count like count follower but you right.
It will be fix soon in a new version.

**Comment by Armanoide** [comment]
The issue is solve with version 1.0.9

**Comment by Armanoide** [comment]
the issue is solve with version **1.0.9**
